### ISSUE TITLE
Compatibility Issue with Iron's Spellbooks 3.15.0

### ISSUE THREAD

**Issue by Zatzx** [pietro-lopes/AllTheLeaks#76]
# Compatibility Issue with Iron's Spellbooks 3.15.0

## Description
All The Leaks v1.0.7 crashes when used with Iron's Spells 'n Spellbooks v3.15.0 due to a missing class reference. The mod works fine with Iron's Spellbooks v3.14.x but fails with the newer version.

## Environment
- **Minecraft Version**: 1.20.1
- **Forge Version**: 47.4.0
- **All The Leaks Version**: 1.0.7+1.20.1-forge
- **Iron's Spells 'n Spellbooks Version**: 3.15.0 (previously worked with 3.14.x)
- **Other Relevant Mods**: Cataclysm: Spellbooks 1.2.7-1.20.1

## Crash Report
```
java.lang.NoClassDefFoundError: io/redspace/ironsspellbooks/entity/mobs/dead_king_boss/DeadKingMusicManager
	at dev.uncandango.alltheleaks.leaks.client.mods.irons_spellbooks.UntrackedIssue002.clearDeadKingMusicManager(UntrackedIssue002.java:17)
```

## Steps to Reproduce
1. Install All The Leaks v1.0.7+1.20.1-forge
2. Install Iron's Spells 'n Spellbooks v3.15.0
3. Launch Minecraft 1.20.1 with Forge 47.4.0
4. Attempt to create a new world or load an existing world
5. Game crashes with `NoClassDefFoundError`

## Expected Behavior
All The Leaks should be compatible with Iron's Spellbooks 3.15.0 and handle any internal changes to the mod's structure.

## Actual Behavior
The game crashes because All The Leaks is trying to access `io.redspace.ironsspellbooks.entity.mobs.dead_king_boss.DeadKingMusicManager`, which appears to have been removed, renamed, or relocated in Iron's Spellbooks 3.15.0.

## Analysis
The crash occurs in `UntrackedIssue002.clearDeadKingMusicManager()` which suggests this is a memory leak fix specifically targeting the Dead King boss music manager. This class either:
- No longer exists in Iron's Spellbooks 3.15.0
- Has been renamed or moved to a different package
- Has been refactored into a different system

## Temporary Workaround
Downgrading to Iron's Spells 'n Spellbooks 3.14.x resolves the crash and restores compatibility.

## Suggested Fix
- Update the Iron's Spellbooks integration to check if the `DeadKingMusicManager` class exists before attempting to access it
- Add version detection for Iron's Spellbooks and handle different versions accordingly
- If the class has been moved, update the package reference
- If the feature has been removed from Iron's Spellbooks, consider removing this specific leak fix or making it conditional

## Additional Context
This appears to be a breaking change between Iron's Spellbooks 3.14.x and 3.15.0. Other users may encounter this issue when updating their modpacks.

Thank you for maintaining this excellent optimization mod!

**Comment by pietro-lopes** [comment]
update to latest version of ATL.
